# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build a branch on commit
on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - name: Get tag
      id: image-tag
      run: |
        echo "::set-output name=tag::$(git rev-parse --short HEAD)"
    - name: build and push docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: onboard.azurecr.io/gitopsnjs
        registry: onboard.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}
        tags: "d-${{steps.image-tag.outputs.tag}}"
        
