name: Build a branch on commit
on:
  push:
    branches:
    - master
   # - dev
   # - stage
    - Test
  #pull_request:
  #  branches:
  #  - dev
  #  - stage
  # - test
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - name: Get tag
      id: image-tag
      run: |
        echo "::set-output name=tag::$(git rev-parse --short HEAD)"
    - name: master - build and push docker image
      if: ${{ github.ref == 'refs/heads/master' }} & {{ github.event.pull_request.merged == 'false' }}
      uses: elgohr/Publish-Docker-Github-Action@master      
      with:
        name: onboard.azurecr.io/gitopsnjs
        registry: onboard.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}       
        tags: "${{steps.image-tag.outputs.tag}}"
        
    - name: Create Pull Request
      if: ${{ success() }}
      uses: repo-sync/pull-request@v2
      id: open-pr
      with:
        destination_branch: "Test"
        source_branch: "master"
        #pr_title: "Pulling ${{ github.ref }} into stage"
        github_token: ${{ secrets.GIT_TOKEN }}
    - name: Slack Notification
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      #with:
        #status: ${{ job.status }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: devops
      
    - name: Test - build and push docker image
      if: ${{ github.ref == 'refs/heads/Test' }}
      uses: elgohr/Publish-Docker-Github-Action@master      
      with:
        name: onboard.azurecr.io/gitopsnjs
        registry: onboard.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}       
        tags: "T-${{steps.image-tag.outputs.tag}}"
