# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Merge Notification
on:
  pull_request:
    #types: 
    #- edited
    branches:
    - dev
    - stage
  
jobs:
  notify:  
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.merged == 'true'}}
    steps:
    - name: Slack Notification        
      uses: rtCamp/action-slack-notify@v2
      with:
        status: "stage-pr-merged"
      env:
        SLACK_USERNAME: 'GitOpsBot'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: 'https://gitopslogo.s3.ap-south-1.amazonaws.com/hexaware.jpg'
        SLACK_CHANNEL: devops
        SLACK_COLOR: '#5DADE2'
        SLACK_TITLE: 'PR Merged by user ${{github.event.pull_request.base.user.login}}'
        #SLACK_MESSAGE: 'PR #${{github.event.pull_request.number}} Branch ${{ github.event.pull_request.base.ref }}'
        SLACK_FOOTER: 'Hexaware GitOps platform'  
   
