name: Update GitOps Repo on PR Merge
on:
  pull_request:
    types:
    - closed
    branches:
    - master
    - stage

jobs:
  stage_merge_job:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'stage'
    runs-on: ubuntu-latest
    steps:
    - name: Clone Application repository    
      uses: actions/checkout@v2
    - name: Get Image tags
      id: image-tag
      run: |
        echo "::set-output name=tag::$(git rev-parse --short HEAD)"
    - name: Clone Gitops repository
      uses: actions/checkout@v2
      with:
        repository: 'rattisyam/GitOpsRepo'
        ref: 'master'
    - name: Install dependencies
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.6.3/yq_linux_amd64.tar.gz
        tar xz yq_linux_amd64.tar.gz 
        mv yq_linux_amd64 /usr/bin/yq
    - name: Update values.staging.yaml
      run: |
        yq e '.image.tag = \"s-${{steps.image-tag.outputs.tag}}\"" -i nodejs/values.staging.yaml
        git commit -am "Updated values.staging.yaml"
        git push origin master


  close_job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merged