# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR Notification
on:
  pull_request:
    types: 
    - opened
    branches:
    - dev
    - stage
  
jobs:
  notify:  
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification        
      uses: rtCamp/action-slack-notify@v2
      with:
        status: "stage-pr-merged"
      env:
        SLACK_USERNAME: 'GitOpsBot'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: 'https://gitopslogo.s3.ap-south-1.amazonaws.com/hexaware.jpg'
        SLACK_CHANNEL: devops
        SLACK_COLOR: '#F4D03F'
        SLACK_TITLE: 'New Pull Request by user ${{github.event.pull_request.base.user.login}}'
        SLACK_MESSAGE: 'PR #${{github.event.pull_request.number}} Branch ${{ github.event.pull_request.base.ref }}'
        SLACK_FOOTER: 'Hexaware GitOps platform'
       
      
   # - name: stage-pr-merge
    #  if: github.event.pull_request.merged == 'true' && ${{ github.ref == 'refs/heads/stage' }}
     # uses: rtCamp/action-slack-notify@v2
      #with:
      #  status: "stage-pr-merged"
      #env:
        #SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       # SLACK_CHANNEL: devops
    #- name: master-pr-merge
      #if: github.event.pull_request.merged == 'true' && ${{github.ref == 'refs/heads/master'}}
     # uses: rtCamp/action-slack-notify@v2
     # with:
       # status: "master-pr-merged"
      #env:
       # SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #SLACK_CHANNEL: devops
      
   
