name: Notification
on:
  repository_dispatch:
    types:
    - run-ok
    - run-notok
jobs:
  onok:
    runs-on: ubuntu-latest
    if: github.event.repository_dispatch.type == 'run-ok'
    steps:
    - name: Send SUCCESS notification to slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: 'GitOpsBot'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: 'https://gitopslogo.s3.ap-south-1.amazonaws.com/hexaware.jpg'
        SLACK_CHANNEL: devops
        SLACK_COLOR: '#58D68D'
        SLACK_TITLE: '${{github.event.client_payload.title}}'
        SLACK_MESSAGE: '${{github.event.client_payload.msg}}'
        SLACK_FOOTER: 'Hexaware GitOps platform'
  onnotok:
    runs-on: ubuntu-latest
    if: github.event.repository_dispatch.type == 'run-notok'
    steps:
    - name: Send FAILURE notification to slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: 'GitOpsBot'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: 'https://gitopslogo.s3.ap-south-1.amazonaws.com/hexaware.jpg'
        SLACK_CHANNEL: devops
        SLACK_COLOR: '#EC7063'
        SLACK_TITLE: '${{github.event.client_payload.title}}'
        SLACK_MESSAGE: '${{github.event.client_payload.msg}}'
        SLACK_FOOTER: 'Hexaware GitOps platform'